### ISSUE TITLE
params.in as an argument does not work

### ISSUE THREAD

**Issue by auraoupa** [bderembl/qgw#8]
is it because it expects 2 arguments ?
cf : 
```
  if (argc == 2)
    strcpy(file_param,argv[1]); // default: params.in
```

**Comment by bderembl** [comment]
I think it is because of the declaration of
`char *file_param = "params.in"; // default param filename`
in extra.h: if we read a filename that is longer than 8 characters , we get an error

It should be something like
`char file_param[80] = "params.in"; // default param filename`

**Comment by auraoupa** [comment]
indeed it was that
